/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "text-text-tertiary": "#fff",
        whitesmoke: "#f3f4f6",
        "text-text-primary": "#000",
        "main-blue": "#2398ff",
        dodgerblue: "#0a80e6",
        gray: {
          "100": "#fafafa",
          "200": "rgba(135, 135, 135, 0.5)",
          "300": "rgba(0, 0, 0, 0.05)",
          "400": "rgba(247, 253, 253, 0.2)",
        },
        "surface-primary-surface": "#2398ff",
        "surface-error": "#fd605d",
        "surface-bg-primary": "#fff",
        "surface-bg-secondary": "#f4f4f4",
        "surface-bg-blue": "#f0f8ff",
        "surface-border": "#eaeaea",
        "text-text-secondary": "#878787",
        "text-text-primary": "#000",
        "colors-text-black": "#000",
        gainsboro: {
          "100": "#dbdfe6",
          "200": "#d9d9d9",
          "300": "#e6e6e6",
          "500": "#ddd",
          "600": "#dbdbdb",
        },
        lightgray: "#d1d1d1",
        "app-background": "#f7fdfd",
        "stroke-light": "#e7eff1",
        headings: "#003d51",
        error: "#e01d40",
        "secondary-button-link": "#09b7aa",
        "primary-button-link": "#019fd5",
        lightsteelblue: "#a9b2c2",
        "success-active": "#00c23b",
        "warning-active": "#fabd48",
        "danger-active": "#d12d26",
        slategray: {
          "100": "#526484",
          "200": "rgba(86, 117, 128, 0.1)",
        },
        stroke: "#567580",
        "placeholder-text": "#74aaa6",
        paragraph: "#3d748f",
        "primary-bright": "#38d5cb",
        brown: "#ba3e36",
        honeydew: "#f0ffec",
        limegreen: {
          "100": "#33ad0b",
          "200": "#2faa06",
        },
        antiquewhite: "#fff3de",
        orange: "#f2a217",
        aliceblue: "#ecf4fe",
        seashell: "#fff0ee",
        tomato: "#e74c3c",
        "table-background": "#f4f4f4",
        mediumslateblue: "#0966ff",
        "light-red": "#f9eeee",
        red: "#fd605d",
        royalblue: {
          "100": "#0c79ff",
          "200": "#1276fa",
        },
        "light-blue": "#f0f8ff",
        khaki: "#f4d35e",
        dimgray: "#5f616e",
        darkslategray: "#1c2b33",
        deepskyblue: "#249dde",
        steelblue: "#0a85c4",
      },
      spacing: {
        "spacing-lg": "24px",
        "spacing-sm": "12px",
        "spacing-md": "16px",
        "radius-lg": "8px",
        "spacing-2": "16px",
        "spacing-xs": "8px",
        "spacing-3": "24px",
        "spacing-1": "8px",
        boundvariablesdata: "1392px",
        boundvariablesdata1: "1392px",
        boundvariablesdata2: "1392px",
      },
      fontFamily: {
        "body-reg": "Manrope",
        "base-md-regular": "Lato",
        "open-sans": "'Open Sans'",
        inter: "Inter",
        "body-xs-semi-bold": "Manrope",
        lato: "Lato",
      },
      borderRadius: {
        "81xl": "100px",
        "45xl": "64px",
        "8xs": "5px",
        "181xl": "200px",
        "77xl": "96px",
        "13xl": "32px",
        "8xs-2": "4.2px",
        "radius-radius-lg": "8px",
        "radiuscomponent-button": "4px",
        "radius-md": "8px",
        "radius-md1": "4px",
      },
    },
    fontSize: {
      "5xs": "8px",
      sm: "14px",
      base: "16px",
      xl: "20px",
      "9xl": "28px",
      lg: "18px",
      "5xl": "24px",
      xs: "12px",
      "3xs": "10px",
      "2xs": "11px",
      "37xl": "56px",
      "15xl": "34px",
      "26xl": "45px",
      "5xs-7": "7.7px",
      "3xs-8": "9.8px",
      "8xs-9": "4.9px",
      "6xs": "7px",
      inherit: "inherit",
    },
    screens: {
      mq1900: {
        raw: "screen and (max-width: 1900px)",
      },
      mq1600: {
        raw: "screen and (max-width: 1600px)",
      },
      mq1425: {
        raw: "screen and (max-width: 1425px)",
      },
      mq1400: {
        raw: "screen and (max-width: 1400px)",
      },
      mq1275: {
        raw: "screen and (max-width: 1275px)",
      },
      lg: {
        max: "1200px",
      },
      mq950: {
        raw: "screen and (max-width: 950px)",
      },
      mq900: {
        raw: "screen and (max-width: 900px)",
      },
      mq825: {
        raw: "screen and (max-width: 825px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};

